name: Playwright Tests

permissions:
  contents: read

on:
  schedule:
    - cron: "0 20 * * 0-4"   # Runs at 7:00 AM AEDT (20:00 UTC) every Monday to Friday
  push:
    branches:
      - master  
  pull_request:
    branches:
      - master  # Run tests when a pull request is created or updated
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4    
  tests-Rooms:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    needs: setup

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*  # Use the version of Node.js your project requires

      # Cache Node.js modules (for npm or yarn)
      - name: Cache Yarn Dependencies
        id: yarn-cache  # Set an ID for the cache step
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        if: steps.yarn-cache.outputs.cache-hit == 'false'
        run: |
          yarn install

      - name : Install playwright-bdd
        run: |
            npm install -D playwright-bdd

      # Cache Playwright browsers to avoid downloading them every run
      - name: Cache Playwright Browsers
        id: playwright-cache  # Set an ID for the cache step
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: Install Playwright Browsers (only runs if cache is not hit)
        # if: steps.playwright-cache.outputs.cache-hit == 'false'
        run: yarn playwright install --with-deps

      # Run tests for each profile
      - name: Run Playwright Tests
        run: 
          yarn test

      - name: Show testContext.json location
        run: |
          find . -name testContext.json

      - name: Print testContext.json contents
        run: |
          cat ./tests/testContext.json || echo "File not found"

      - name: Upload Playwright Test Results (Admin)
        if: always()  # Always run, even if the tests fail
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/ # Update this path based on your Playwright test result directory
          retention-days: 30